Vagrant.configure(2) do |config|
  
  config.vm.box = "ubuntu/trusty64" # BOX명
  config.vm.synced_folder ".", "/vagrant", type:"nfs" # 파일 싱크
    
  config.vm.provider "virtualbox" do |v| # 사양 설정
      v.memory = 1024 # mysql 5.6은 최소 1g이상 메모리가 필요
      v.cpus = 2
  end

  config.vm.provision "init", type: "shell", path: "ubuntu-init.sh" # 초기 설치
  config.vm.provision "vhost", type: "shell", path: "ubuntu-vhost.sh" # 버추얼호스트 변경

  config.vm.network "private_network", ip: "192.168.33.10"
  #config.vm.network "public_network", ip: "192.168.20.99"
  config.vm.network "forwarded_port", guest: 80, host: 9000 # 호스트와 연결할 포트 설정
  
end